esphome:
  name: 8-gang-switch
  friendly_name: 8-Gang-switch

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "rLMdoILDTqYcA6Kx1ZqY0tjwpEmz9QhVwxs1LKqLbFI="

ota:
  - platform: esphome
    password: "446046e6342d32129106a8c65d80f289"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "8-Gang-Switch Fallback Hotspot"
    password: "nW5zSCbzewIO"

captive_portal:
switch:
  - platform: gpio
    pin: GPIO12
    name: Switch1
    id: Switch1
  - platform: gpio
    pin: GPIO13
    name: Switch2
    id: Switch2
  - platform: gpio
    pin: GPIO14
    name: Switch3
    id: Switch3
  - platform: gpio
    pin: GPIO27
    name: Switch4
    id: Switch4
  - platform: gpio
    pin: GPIO26
    name: Switch5
    id: Switch5
  - platform: gpio
    pin: GPIO25
    name: Switch6
    id: Switch6
  - platform: gpio
    pin: GPIO33
    name: Switch7
    id: Switch7
  - platform: gpio
    pin: GPIO32
    name: Switch8
    id: Switch8    